"""Request-scoped context propagation.

A per-request id is generated by the HTTP middleware and stored in a
context variable so every log line emitted while handling that request
(including from services) can be correlated with it.
"""

from __future__ import annotations

from contextvars import ContextVar

# Default "-" is used outside an active HTTP request (tests, scripts).
_request_id: ContextVar[str] = ContextVar("request_id", default="-")


def get_request_id() -> str:
    """Return the id of the current request (or ``"-"`` outside requests)."""
    return _request_id.get()


def set_request_id(request_id: str) -> None:
    """Bind ``request_id`` to the current async context."""
    _request_id.set(request_id)